services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: globalcoins-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  globalcoins-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    depends_on:
      - postgres
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app/
        – /node_module/