networks:
  globalcoins-api_default:
    driver: bridge
    external: true

services:
  postgres:
    container_name: globalcoins-postgres
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    ports:
      - "5432:5432"
    volumes:
      - globalcoins_pg_data:/var/lib/postgresql/data
    networks:
      - globalcoins-api_default
    expose:
      - 5432

  globalcoins-api:
    container_name: globalcoins-api
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    depends_on:
      - postgres
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app/
        – /node_module/
    networks:
      - globalcoins-api_default

volumes: 
  globalcoins_pg_data:
